### ISSUE TITLE
If no tile can be placed, you can't end a round.

### ISSUE THREAD

**Issue by gs-mancs** [ondras/rri#1]
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/5958330/72162791-8108e980-33ba-11ea-90b5-25869a61091f.png">

As per game rules, if you're unable to place a tile, you simply don't have to.
Player can't get to the final score without completing the game.
Makes it impossible to challenge other players for the lowest possible score. 🤣

**Comment by ondras** [comment]
Good point! Thanks @GaborSuranyi.

What solution do you prefer? Unlocking the "end round" button once no tile can be placed? What about bonus tiles? They might be the (only one) option to continue playing, even though that is not the case for your screenshot.

**Comment by gs-mancs** [comment]
Well, the minimum requirement for placing a tile is that one side, has to be able to connect to any available tile. So your scenario could only happen if let's say all rail links are blocked off, but you have a remaining bonus tile with a road side, and your current remaining tiles are rail only.

Maybe highlight the unplaceable tile(s) in red, and unlock the next round button.
But there should be an option to play the bonus tile, and then re-evaluate whether or not the previously unplacable tile could now be placed. (since most bonus tiles convert from road to rail.)

**Comment by ondras** [comment]
Fixed! :)
