### ISSUE TITLE
Link to manual

### ISSUE THREAD

**Issue by alexanderkogan** [ondras/rri#15]
The manual from the official source is not available anymore.
You could link the BGG document https://boardgamegeek.com/file/download_redirect/eb4b3f00ba5dfbac38dcf69ce4f2a3f9b25ab60d1790d65c/RRI_BLU_Rulebook_ENG_v05_light.pdf

I'll make a PR, when I'm at my laptop, if nobody comes around to it before.

**Comment by ondras** [comment]
Ah, thanks for letting me know. I will fix that.

**Comment by ondras** [comment]
Looks like the alternative official link is https://www.dropbox.com/s/pu4yifwuhfivwmg/RRI_BLUE_Rulebook-EN_v02_Web.pdf

**Comment by ondras** [comment]
Updated.
