### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tuukka** [ondras/rri#17]
Congratulations and thanks for a slick implementation! Have you considered adding an open source license for the code?

**Comment by ondras** [comment]
Okay, will add.

**Comment by ondras** [comment]
Done :-)

**Comment by tuukka** [comment]
Awesome, thank you! Are you still interested in some bug reports or only pull requests? 😉

**Comment by ondras** [comment]
Feel free to report any bugs you encounter. I cannot guarantee any time window for fixing, but I will certainly give them some thought ;-)
