### ISSUE TITLE
Tiles sometimes rendered too small

### ISSUE THREAD

**Issue by tuukka** [ondras/rri#18]
On desktop browsers, I have to zoom out the page a bit. (This changes `devicePixelRatio` on the fly).

This causes some tiles to render in too small scale after clicking "End round". Just a guess: I see board-canvas.ts uses `const DPR = devicePixelRatio;` but draw-context.ts uses `devicePixelRatio` directly.

Most surprising to me is how the tile size can vary among tiles played in the same round. If I re-connect to a multiplayer game, the tiles render correctly again. (The tiles are re-drawn with a stable `devicePixelRatio`?)

Here's a few screenshots that show the issue:

![rri-tile-scaling-issue](https://user-images.githubusercontent.com/76985/213808162-58b8c00c-9fdd-4dd3-9678-6a8367822878.png)

![rri-tile-scaling-reduced](https://user-images.githubusercontent.com/76985/213817891-725d57ed-793c-4d5b-ae42-f72cb54b4066.png)

**Comment by ondras** [comment]
I see. Interesting issue; I believe you correctly discovered the `const` vs. `at runtime` DPR discrepancy and cause.

Will try using the fixed initial DPR value in all places to see what happens.

**Comment by ondras** [comment]
@tuukka I just published a version that uses fixed DPR. Please check it out and test whether it works for you.

**Comment by ondras** [comment]
Hopefully the issue has been resolved.
