### ISSUE TITLE
Lake didn't fill in

### ISSUE THREAD

**Issue by catdadreed** [ondras/rri#19]
Hi folks,
*Love this game!*
I think the lake should've filled in here (but am not sure).
![railroad-ink 23-02-28 lakes, not fill](https://user-images.githubusercontent.com/126635915/222029731-7d92eaa3-73ae-45fa-aac8-f5b9ad79f0db.png)
Thanks!

**Comment by ondras** [comment]
The [rules](https://www.dropbox.com/s/pu4yifwuhfivwmg/RRI_BLUE_Rulebook-EN_v02_Web.pdf) say:

> If a space has 3 sides adjacent to the open sides of Lakes, it must be completely filled with water immediately.

...but your empty spaces only have 2 sides adjacent to open sides of Lakes.

**Comment by catdadreed** [comment]
Okay I saw that in the rules, and wasn't sure how it would be interpreted in this case.  Good to know, thank you!
