### ISSUE TITLE
Cannot rotate tile on mobile

### ISSUE THREAD

**Issue by meridius** [ondras/rri#2]
Not sure how the desktop behaves but I couldn't find out how to rotate the tile on mobile Chrome.

**Comment by ondras** [comment]
Tiles are rotated by clicking (touching) them after being placed. Just tried on mobile Chrome, seems to work normally.

**Comment by meridius** [comment]
Sorry, your are right, it is working now. Previously it just removed the tile instead.

**Comment by ondras** [comment]
Removing happens when you hold the tile for a bit. Not perfect from a UX standpoint, but simple enough.
