### ISSUE TITLE
No points for the complete lake 

### ISSUE THREAD

**Issue by kshpdr** [ondras/rri#24]
While playing, we found out that in the following setting game doesn't count a complete lake:

<img width="673" alt="Screenshot 2023-12-17 at 19 57 03" src="https://github.com/ondras/rri/assets/62385262/6c661cfd-b30d-4128-8a21-ab91ca48e3e3">

**Comment by ondras** [comment]
Sounds like an issue already discussed before: https://github.com/ondras/rri/issues/19

**Comment by kshpdr** [comment]
You're right!
