### ISSUE TITLE
Tiles are still Valid after removing of others

### ISSUE THREAD

**Issue by Jack-Spirio** [ondras/rri#3]
When you place two tiles and then remove the first the second will still be allowed even though it isn't legal normally. That way you can start to draw in the middle of the board if you want

**Comment by ondras** [comment]
Hi @Jack-Spirio ,
thanks for your bugreport. Do you suggest any particular action to happen in this case?

**Comment by Jack-Spirio** [comment]
Maybe mark that tile in some color

**Comment by sebastian-zarzycki-apzumi** [comment]
Or just remove the whole chain of unconnected tiles from the board.

**Comment by ondras** [comment]
> Or just remove the whole chain of unconnected tiles from the board.

I like the simplicity of this solution. No need to introduce a new color (and a problematic game state).

**Comment by kino90** [comment]
+1, I also suggest to solve this by removing all invalid tiles after removing the first tile

Btw: thanks for this repo, I love RRI and your version is just perfect (and also thanks for making it open source!)

**Comment by ondras** [comment]
> +1, I also suggest to solve this by removing all invalid tiles after removing the first tile

Turns out this is more difficult than I initially thought!

Detecting an invalid tile is complex, because it can be correctly connected into another invalid tile (say you added three tiles in a row, then removed the first one).

**Comment by casellimarco** [comment]
This happens also in case of rotation of tiles. One option is that when the user declares the end of turn there is a checker of the sanity of the board. 

The checker can use the same technology that suggests the cell where to put the tile:
- Remove the turn tiles from the board and store them together with location and direction decided by the user.
- Try to populate the board again, by picking the first tile and see if the location is between the suggested ones and the direction matches.
- If it fails try with the next tile, and so on. 
- Once a tile is placed start again from the first unplaced tile (it can be one which was not possible to place in the previous loop)
- If some of the tiles cannot be allocated the board is incorrect and the unplaced tiles are the cause of the incorrect configuration.

Another approach would be to let the user to just edit the last placed tile (and the if the last one is removed the second last and so on..) but probably it would be ideal, having a quick way to change the configuration is quite important.

Edit: add missing negation in the last step

**Comment by ondras** [comment]
> * Remove the turn tiles from the board and store them together with location and direction decided by the user.
> 
> * Try to populate the board again, by picking the first tile and see if the location is between the suggested ones and the direction matches.

Perhaps this is all what is needed! Because if the checker fails to re-place a tile, it means the board is invalid (preventing ending a turn). It only needs to place tiles in the same order they were placed by the user... am I right?

**Comment by ondras** [comment]
> Perhaps this is all what is needed! Because if the checker fails to re-place a tile, it means the board is invalid (preventing ending a turn). It only needs to place tiles in the same order they were placed by the user... am I right?

No, I was not right. Re-placing them afterwards is not sufficient.


>     * If some of the tiles can be allocated the board is incorrect and the unplaced tiles are the cause of the incorrect configuration.

I am not sure I understand this point. Generally speaking, I am still unsure about the "board sanity checker" algorithm.

**Comment by casellimarco** [comment]
> > ```
> > * If some of the tiles can**NOT** be allocated the board is incorrect and the unplaced tiles are the cause of the incorrect configuration.
> > ```
> 
> I am not sure I understand this point. Generally speaking, I am still unsure about the "board sanity checker" algorithm.

Sorry, I forgot a NOT in the last step, I guess it is the main source of confusion.

Does it convince you now? 
As you notice unfortunately you have to try all the permutations to be sure but they are at most (n^2+n)/2 where n is the number of tiles, and in practice they are gonna be many less.

**Comment by ondras** [comment]
> Does it convince you now?

Yeah, I think I get it now. Will let you know once I get to implementing this. Sounds straightforward.

**Comment by ondras** [comment]
I hope I applied the proposed fix correctly. Please, @Jack-Spirio and @casellimarco , could you test at https://ondras.github.io/rri/ ?

**Comment by casellimarco** [comment]
I tested it and I also went through the implementation, well done! Many thanks for the speedy fix!

**Comment by Jack-Spirio** [comment]
Works great, thanks a lot
