### ISSUE TITLE
[feature request] Personal score visible / updated during the game?

### ISSUE THREAD

**Issue by sebastian-zarzycki-apzumi** [ondras/rri#5]
One of the players today suggested, that it could be a global option per game, to see your own score all the time (but updated after finishing round, to prevent "optimizing"). This helps new players internalize the value of their moves.

**Comment by ondras** [comment]
I am ambivalent about this one. I see it as a possible quality-of-life improvement, but it also somewhat contrasts with the main goal of mirroring the board game experience as much as possible. Also, the current UI is intentionally minimal and does not really offer an ideal place to put score to. Perhaps the "waiting for X players" line could be enriched by the current score.

**Comment by sebastian-zarzycki-apzumi** [comment]
I've used the same reasoning when explaining to players why this (probably) isn't there. Then again, online version already highlights valid placements - and that isn't something players have for physical version, so differences are bound to happen. Might as well use it to advantage.

Having said that, you're already displaying the score at the bottom when the game ends. I thought it would be easy to reuse that? (just hiding other players, etc.).

**Comment by ondras** [comment]
> Having said that, you're already displaying the score at the bottom when the game ends. I thought it would be easy to reuse that? (just hiding other players, etc.).

*Implementing* the feature is currently really trivial. I just cannot decide whether I *want* to do/have it :-)

**Comment by ondras** [comment]
(the intermediate score is already computed and uploaded, becase I plan to add a score-over-time chart to future versions)

**Comment by sebastian-zarzycki-apzumi** [comment]
Yeah, I've actually browsed the source code before submitting this :). Just so that it is clear - my idea was for players to decide before the game, whether this is enabled for all, or not (checkbox in UI or maybe even a simple yes/no dialog). This way players can experience the game the way they prefer.

Well, it's up to you, of course. Thanks for this great implementation, anyway!

**Comment by ondras** [comment]
Implemented :-)

**Comment by sebastian-zarzycki-apzumi** [comment]
Nice! Thank you!
